<?php

/**
 * When viewing a Hello World Article on the Drupal site, the phrase "Content starts here!" should appear in an italic typeface as the first line of content on the page.
 */
function hello_world_preprocess_node(&$variables) {
	if($variables['node']->getType() == 'hello_world_article'){
		
		$variables['content']['hello_world'] = [
			'#theme' => 'markup',
			'#title' => '',
			#'view_mode' => 'full',
			'#entity_type' => 'node',
			'#bundle' => 'hello_world_article',
			#'#object' => $variables['content']['body']['#object'],
			#'#field_name' => 'hello_world',
			'#label_display' => 'hidden',
			'#weight' => -99,
			'#formatter' => 'text_default',
			'#is_multiple' => false,
			0 => [
				'#type' => 'processed_text',
				'#text' => '<span style="italic">Content starts here!</span>',
				'#format' => 'full_html',
				'#langcode' => 'en',
			]
		];
	}
}

